// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: chat/v1/model.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Flipcash_Chat_V1_ChatType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case contactDm // = 1
  case tipDm // = 2
  case group // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .contactDm
    case 2: self = .tipDm
    case 3: self = .group
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .contactDm: return 1
    case .tipDm: return 2
    case .group: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Flipcash_Chat_V1_ChatType] = [
    .unknown,
    .contactDm,
    .tipDm,
    .group,
  ]

}

public struct Flipcash_Chat_V1_Metadata: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatID: Flipcash_Common_V1_ChatId {
    get {return _storage._chatID ?? Flipcash_Common_V1_ChatId()}
    set {_uniqueStorage()._chatID = newValue}
  }
  /// Returns true if `chatID` has been explicitly set.
  public var hasChatID: Bool {return _storage._chatID != nil}
  /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
  public mutating func clearChatID() {_uniqueStorage()._chatID = nil}

  /// The type of chat
  public var type: Flipcash_Chat_V1_ChatType {
    get {return _storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  /// Members of this chat
  ///
  /// For large group chats, this is a subset of all members. Use
  /// RosterSummary.member_count to infer if there are more members.
  public var members: [Flipcash_Chat_V1_Member] {
    get {return _storage._members}
    set {_uniqueStorage()._members = newValue}
  }

  /// The last message in this chat. Withheld, along with
  /// latest_event_sequence, from a viewer who may not read the chat. May be
  /// redacted (see messaging.v1.Message.redacted) when the read was made
  /// under a messaging.v1.ViewMode other than FULL.
  public var lastMessage: Flipcash_Messaging_V1_Message {
    get {return _storage._lastMessage ?? Flipcash_Messaging_V1_Message()}
    set {_uniqueStorage()._lastMessage = newValue}
  }
  /// Returns true if `lastMessage` has been explicitly set.
  public var hasLastMessage: Bool {return _storage._lastMessage != nil}
  /// Clears the value of `lastMessage`. Subsequent reads from it will return its default value.
  public mutating func clearLastMessage() {_uniqueStorage()._lastMessage = nil}

  /// The timestamp of the last activity in this chat
  public var lastActivity: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._lastActivity ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._lastActivity = newValue}
  }
  /// Returns true if `lastActivity` has been explicitly set.
  public var hasLastActivity: Bool {return _storage._lastActivity != nil}
  /// Clears the value of `lastActivity`. Subsequent reads from it will return its default value.
  public mutating func clearLastActivity() {_uniqueStorage()._lastActivity = nil}

  /// The chat's head event sequence — the value of the most recent event in its
  /// event log. A client compares this against its locally stored cursor for
  /// the chat to decide whether catch-up is needed: if its cursor is behind, it
  /// calls Messaging.GetDelta; if equal, it is current and can skip it.
  ///
  /// This is NOT derivable from last_message: an edit or deletion of an older
  /// message advances the head without changing last_message, so this value can
  /// exceed last_message.event_sequence. It is the same head reported by
  /// GetDeltaResponse.latest_sequence.
  public var latestEventSequence: UInt64 {
    get {return _storage._latestEventSequence}
    set {_uniqueStorage()._latestEventSequence = newValue}
  }

  /// Whether this chat is hidden from the requesting owner's chat list.
  /// Per-viewer and server-computed (e.g. the chat's peer is on the caller's
  /// blocklist). Clients should exclude hidden chats from the primary DM list.
  public var isHidden: Bool {
    get {return _storage._isHidden}
    set {_uniqueStorage()._isHidden = newValue}
  }

  /// Title for this chat. Only supported for group chats
  public var title: String {
    get {return _storage._title}
    set {_uniqueStorage()._title = newValue}
  }

  /// Picture for this chat. Only supported for group chats
  public var picture: Flipcash_Blob_V1_Media {
    get {return _storage._picture ?? Flipcash_Blob_V1_Media()}
    set {_uniqueStorage()._picture = newValue}
  }
  /// Returns true if `picture` has been explicitly set.
  public var hasPicture: Bool {return _storage._picture != nil}
  /// Clears the value of `picture`. Subsequent reads from it will return its default value.
  public mutating func clearPicture() {_uniqueStorage()._picture = nil}

  /// Chat roster summary
  public var rosterSummary: Flipcash_Chat_V1_RosterSummary {
    get {return _storage._rosterSummary ?? Flipcash_Chat_V1_RosterSummary()}
    set {_uniqueStorage()._rosterSummary = newValue}
  }
  /// Returns true if `rosterSummary` has been explicitly set.
  public var hasRosterSummary: Bool {return _storage._rosterSummary != nil}
  /// Clears the value of `rosterSummary`. Subsequent reads from it will return its default value.
  public mutating func clearRosterSummary() {_uniqueStorage()._rosterSummary = nil}

  /// Rules governing participation in this chat. Only supported for group
  /// chats. If not set, the chat has no participation requirements.
  public var rules: Flipcash_Chat_V1_Rules {
    get {return _storage._rules ?? Flipcash_Chat_V1_Rules()}
    set {_uniqueStorage()._rules = newValue}
  }
  /// Returns true if `rules` has been explicitly set.
  public var hasRules: Bool {return _storage._rules != nil}
  /// Clears the value of `rules`. Subsequent reads from it will return its default value.
  public mutating func clearRules() {_uniqueStorage()._rules = nil}

  /// Per-viewer chat state, including what the viewer may do in the chat.
  /// Absent when the chat holds nothing about them; always set for a member.
  public var viewerState: Flipcash_Chat_V1_ViewerState {
    get {return _storage._viewerState ?? Flipcash_Chat_V1_ViewerState()}
    set {_uniqueStorage()._viewerState = newValue}
  }
  /// Returns true if `viewerState` has been explicitly set.
  public var hasViewerState: Bool {return _storage._viewerState != nil}
  /// Clears the value of `viewerState`. Subsequent reads from it will return its default value.
  public mutating func clearViewerState() {_uniqueStorage()._viewerState = nil}

  /// The user that created this chat. Set only for group chats.
  public var creator: Flipcash_Common_V1_UserId {
    get {return _storage._creator ?? Flipcash_Common_V1_UserId()}
    set {_uniqueStorage()._creator = newValue}
  }
  /// Returns true if `creator` has been explicitly set.
  public var hasCreator: Bool {return _storage._creator != nil}
  /// Clears the value of `creator`. Subsequent reads from it will return its default value.
  public mutating func clearCreator() {_uniqueStorage()._creator = nil}

  /// Whether messages in this chat are end-to-end encrypted (see
  /// messaging.v1.EncryptedContent). Only supported for DMs (CONTACT_DM or
  /// TIP_DM); always false for group chats.
  ///
  /// Used to migrate DMs to E2EE: when true, clients send all new content in
  /// the chat as EncryptedContent. When false, clients send content in the
  /// clear. Existing messages are not re-encrypted, so a chat may hold a mix
  /// of both.
  ///
  /// This is a transitional flag. Once E2EE has launched, clients should
  /// always end-to-end encrypt DMs regardless of this value, and it will be
  /// deprecated.
  public var useE2Ee: Bool {
    get {return _storage._useE2Ee}
    set {_uniqueStorage()._useE2Ee = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Rules define the requirements a user must satisfy to participate in a chat.
///
/// Rules are split into two classes, each of which is independently optional:
///  - ListenerRules gate reading and joining the chat
///  - SpeakerRules gate sending messages in the chat
///
/// All rules within a class must be satisfied. Speaker rules are applied in
/// addition to listener rules: a user must be able to listen before they can
/// speak.
public struct Flipcash_Chat_V1_Rules: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Rules to read and join the chat. If empty, anyone can read and join.
  public var listener: [Flipcash_Chat_V1_ListenerRules] = []

  /// Rules to send messages in the chat. If empty, any member can send
  /// messages.
  public var speaker: [Flipcash_Chat_V1_SpeakerRules] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ListenerRules are the rules a user must satisfy to read and join a chat
public struct Flipcash_Chat_V1_ListenerRules: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Flipcash_Chat_V1_ListenerRules.OneOf_Kind? = nil

  public var minimumBalance: Flipcash_Chat_V1_MinimumBalanceRequirement {
    get {
      if case .minimumBalance(let v)? = kind {return v}
      return Flipcash_Chat_V1_MinimumBalanceRequirement()
    }
    set {kind = .minimumBalance(newValue)}
  }

  public var staff: Flipcash_Chat_V1_StaffRequirement {
    get {
      if case .staff(let v)? = kind {return v}
      return Flipcash_Chat_V1_StaffRequirement()
    }
    set {kind = .staff(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kind: Equatable, Sendable {
    case minimumBalance(Flipcash_Chat_V1_MinimumBalanceRequirement)
    case staff(Flipcash_Chat_V1_StaffRequirement)

  }

  public init() {}
}

/// SpeakerRules are the rules a user must satisfy to send messages in a chat
public struct Flipcash_Chat_V1_SpeakerRules: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Flipcash_Chat_V1_SpeakerRules.OneOf_Kind? = nil

  public var minimumBalance: Flipcash_Chat_V1_MinimumBalanceRequirement {
    get {
      if case .minimumBalance(let v)? = kind {return v}
      return Flipcash_Chat_V1_MinimumBalanceRequirement()
    }
    set {kind = .minimumBalance(newValue)}
  }

  public var staff: Flipcash_Chat_V1_StaffRequirement {
    get {
      if case .staff(let v)? = kind {return v}
      return Flipcash_Chat_V1_StaffRequirement()
    }
    set {kind = .staff(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kind: Equatable, Sendable {
    case minimumBalance(Flipcash_Chat_V1_MinimumBalanceRequirement)
    case staff(Flipcash_Chat_V1_StaffRequirement)

  }

  public init() {}
}

/// StaffRequirement requires the user to be a Flipcash staff member, as
/// indicated by UserFlags.is_staff.
public struct Flipcash_Chat_V1_StaffRequirement: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// MinimumBalanceRequirement requires a user to hold a minimum balance,
/// denominated in fiat, in an acceptable mint.
public struct Flipcash_Chat_V1_MinimumBalanceRequirement: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The minimum balance, denominated in fiat
  public var amount: Flipcash_Common_V1_FiatPaymentAmount {
    get {return _amount ?? Flipcash_Common_V1_FiatPaymentAmount()}
    set {_amount = newValue}
  }
  /// Returns true if `amount` has been explicitly set.
  public var hasAmount: Bool {return self._amount != nil}
  /// Clears the value of `amount`. Subsequent reads from it will return its default value.
  public mutating func clearAmount() {self._amount = nil}

  /// The mints the balance may be held in. If empty, the requirement applies
  /// to all mints. Otherwise, it applies only to the one listed mint.
  ///
  /// Currently limited to at most one mint. This is a repeated field so that
  /// multiple mints can be specified in the future.
  public var mints: [Flipcash_Common_V1_PublicKey] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _amount: Flipcash_Common_V1_FiatPaymentAmount? = nil
}

public struct Flipcash_Chat_V1_Member: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userID: Flipcash_Common_V1_UserId {
    get {return _storage._userID ?? Flipcash_Common_V1_UserId()}
    set {_uniqueStorage()._userID = newValue}
  }
  /// Returns true if `userID` has been explicitly set.
  public var hasUserID: Bool {return _storage._userID != nil}
  /// Clears the value of `userID`. Subsequent reads from it will return its default value.
  public mutating func clearUserID() {_uniqueStorage()._userID = nil}

  /// The user profile for this member. It contains a subset of identifiers
  /// that can be publicly viewed within the chat.
  public var userProfile: Flipcash_Profile_V1_UserProfile {
    get {return _storage._userProfile ?? Flipcash_Profile_V1_UserProfile()}
    set {_uniqueStorage()._userProfile = newValue}
  }
  /// Returns true if `userProfile` has been explicitly set.
  public var hasUserProfile: Bool {return _storage._userProfile != nil}
  /// Clears the value of `userProfile`. Subsequent reads from it will return its default value.
  public mutating func clearUserProfile() {_uniqueStorage()._userProfile = nil}

  /// Chat message state for this member.
  ///
  /// If set, the list may contain DELIVERED and READ pointers. SENT pointers
  /// are only shared between the sender and server, to indicate persistence.
  /// Hydrated for a DM's participants; a group member's are never carried.
  public var pointers: [Flipcash_Messaging_V1_Pointer] {
    get {return _storage._pointers}
    set {_uniqueStorage()._pointers = newValue}
  }

  /// When the member most recently joined the chat. A member who left and
  /// rejoined carries the rejoin time.
  ///
  /// Set for a group's members on a Chat.GetRoster page and on a
  /// RosterUpdate.MemberJoined — the carriers a client builds its member
  /// list from. Unset on Metadata.members, which carries only the viewer's
  /// own entry, and never set for a DM's participants, whose roster is fixed
  /// at creation.
  public var joinedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._joinedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._joinedAt = newValue}
  }
  /// Returns true if `joinedAt` has been explicitly set.
  public var hasJoinedAt: Bool {return _storage._joinedAt != nil}
  /// Clears the value of `joinedAt`. Subsequent reads from it will return its default value.
  public mutating func clearJoinedAt() {_uniqueStorage()._joinedAt = nil}

  /// The roster version at which the member most recently joined: the
  /// version RosterSummary.version moved to on that transition, so it equals
  /// roster_summary.version on the RosterUpdate.MemberJoined that announced
  /// it. Zero for a member joined at the chat's creation and for every DM
  /// participant. In future it moves with any change to what the chat
  /// records about the member (e.g. a role), as RosterSummary.version does.
  ///
  /// A client merges what it holds for a user by this version: the greater
  /// wins, so a GetRoster page that trails the stream (see GetRoster)
  /// cannot resurrect a member the stream has already removed. Set wherever
  /// joined_at is; a DM participant's is zero by that rule too.
  public var version: UInt64 {
    get {return _storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// RosterSummary describes a chat's roster — its member list — without
/// containing it: what a client needs in order to know whether its copy of
/// that list is stale, without holding the list.
///
/// It says nothing about member profiles. Profiles are hydrated afresh onto
/// every response that carries a member, and a profile change never moves
/// this summary.
public struct Flipcash_Chat_V1_RosterSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Number of currently joined members. For a large group chat,
  /// Metadata.members is a subset of the roster; this is its true size, and
  /// Chat.GetRoster pages the roster itself.
  public var memberCount: UInt64 = 0

  /// Version of the roster: advanced by exactly one on every change to the
  /// membership records — a member joining, a member leaving, and in future
  /// any change to what the chat records about a member (e.g. a role) — and
  /// never by an idempotent no-op or a profile change. A viewer's own state
  /// (see ViewerState) is not part of the roster: it is private to that
  /// viewer, carries its own version, and never moves this one.
  ///
  /// Opaque to clients. Compare it against the last value seen: a different
  /// value means the cached member list may be stale and should be refetched.
  /// On a stream, apply a greater value and drop the rest, so delivery order
  /// does not matter. It is compared the same way as ReactionSummary.version
  /// and, like it, is NOT the chat event sequence: there is no delta to fetch
  /// against it, only a refetch of the members.
  public var version: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Flipcash_Chat_V1_MetadataUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Flipcash_Chat_V1_MetadataUpdate.OneOf_Kind? = nil

  public var fullRefresh: Flipcash_Chat_V1_MetadataUpdate.FullRefresh {
    get {
      if case .fullRefresh(let v)? = kind {return v}
      return Flipcash_Chat_V1_MetadataUpdate.FullRefresh()
    }
    set {kind = .fullRefresh(newValue)}
  }

  public var lastActivityChanged: Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged {
    get {
      if case .lastActivityChanged(let v)? = kind {return v}
      return Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged()
    }
    set {kind = .lastActivityChanged(newValue)}
  }

  public var viewerStateChanged: Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged {
    get {
      if case .viewerStateChanged(let v)? = kind {return v}
      return Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged()
    }
    set {kind = .viewerStateChanged(newValue)}
  }

  public var titleChanged: Flipcash_Chat_V1_MetadataUpdate.TitleChanged {
    get {
      if case .titleChanged(let v)? = kind {return v}
      return Flipcash_Chat_V1_MetadataUpdate.TitleChanged()
    }
    set {kind = .titleChanged(newValue)}
  }

  public var pictureChanged: Flipcash_Chat_V1_MetadataUpdate.PictureChanged {
    get {
      if case .pictureChanged(let v)? = kind {return v}
      return Flipcash_Chat_V1_MetadataUpdate.PictureChanged()
    }
    set {kind = .pictureChanged(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kind: Equatable, Sendable {
    case fullRefresh(Flipcash_Chat_V1_MetadataUpdate.FullRefresh)
    case lastActivityChanged(Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged)
    case viewerStateChanged(Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged)
    case titleChanged(Flipcash_Chat_V1_MetadataUpdate.TitleChanged)
    case pictureChanged(Flipcash_Chat_V1_MetadataUpdate.PictureChanged)

  }

  /// Refreshes the entire chat metadata
  public struct FullRefresh: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var metadata: Flipcash_Chat_V1_Metadata {
      get {return _metadata ?? Flipcash_Chat_V1_Metadata()}
      set {_metadata = newValue}
    }
    /// Returns true if `metadata` has been explicitly set.
    public var hasMetadata: Bool {return self._metadata != nil}
    /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
    public mutating func clearMetadata() {self._metadata = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _metadata: Flipcash_Chat_V1_Metadata? = nil
  }

  /// The last activity timestamp has changed to a newer value
  public struct LastActivityChanged: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var newLastActivity: SwiftProtobuf.Google_Protobuf_Timestamp {
      get {return _newLastActivity ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
      set {_newLastActivity = newValue}
    }
    /// Returns true if `newLastActivity` has been explicitly set.
    public var hasNewLastActivity: Bool {return self._newLastActivity != nil}
    /// Clears the value of `newLastActivity`. Subsequent reads from it will return its default value.
    public mutating func clearNewLastActivity() {self._newLastActivity = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _newLastActivity: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  }

  /// The receiving user's own state for the chat has changed
  public struct ViewerStateChanged: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var viewerState: Flipcash_Chat_V1_ViewerState {
      get {return _viewerState ?? Flipcash_Chat_V1_ViewerState()}
      set {_viewerState = newValue}
    }
    /// Returns true if `viewerState` has been explicitly set.
    public var hasViewerState: Bool {return self._viewerState != nil}
    /// Clears the value of `viewerState`. Subsequent reads from it will return its default value.
    public mutating func clearViewerState() {self._viewerState = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _viewerState: Flipcash_Chat_V1_ViewerState? = nil
  }

  /// The chat's title has changed (e.g. via Chat.EditChat). Delivered to the
  /// chat's members, including the editor's other devices. Best-effort and
  /// applied as received; a client that suspects a miss refetches the chat
  /// via Chat.GetChat.
  public struct TitleChanged: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The new title, replacing Metadata.title.
    public var newTitle: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  /// The chat's picture has changed (e.g. via Chat.EditChat). Delivered to
  /// the chat's members, including the editor's other devices. Best-effort
  /// and applied as received; a client that suspects a miss refetches the
  /// chat via Chat.GetChat.
  public struct PictureChanged: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The new picture, with the renditions the server derived, replacing
    /// Metadata.picture.
    public var newPicture: Flipcash_Blob_V1_Media {
      get {return _newPicture ?? Flipcash_Blob_V1_Media()}
      set {_newPicture = newValue}
    }
    /// Returns true if `newPicture` has been explicitly set.
    public var hasNewPicture: Bool {return self._newPicture != nil}
    /// Clears the value of `newPicture`. Subsequent reads from it will return its default value.
    public mutating func clearNewPicture() {self._newPicture = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _newPicture: Flipcash_Blob_V1_Media? = nil
  }

  public init() {}
}

/// RosterUpdate is a best-effort, real-time change to a chat's roster — a
/// member joining (e.g. via Chat.JoinChat, or as the first member via
/// Chat.StartChat) or leaving (e.g. via Chat.LeaveChat). It is delivered to
/// the chat's members, including the affected user's other devices.
///
/// Roster changes are a convergent overlay, so these ride the event stream
/// OUTSIDE the gap-detected event log. Clients apply them by roster_summary
/// version as described on RosterSummary: a greater version than the one held
/// means the cached member list is stale and this update should be applied; a
/// lesser or equal version should be dropped, so delivery order does not
/// matter. A missed update is not caught up via GetDelta but reconciled by
/// refetching the roster when a client observes a version it cannot reconcile.
public struct Flipcash_Chat_V1_RosterUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Flipcash_Chat_V1_RosterUpdate.OneOf_Kind? = nil

  public var memberJoined: Flipcash_Chat_V1_RosterUpdate.MemberJoined {
    get {
      if case .memberJoined(let v)? = kind {return v}
      return Flipcash_Chat_V1_RosterUpdate.MemberJoined()
    }
    set {kind = .memberJoined(newValue)}
  }

  public var memberLeft: Flipcash_Chat_V1_RosterUpdate.MemberLeft {
    get {
      if case .memberLeft(let v)? = kind {return v}
      return Flipcash_Chat_V1_RosterUpdate.MemberLeft()
    }
    set {kind = .memberLeft(newValue)}
  }

  /// The chat's roster summary after this change, applied by version as
  /// described above.
  public var rosterSummary: Flipcash_Chat_V1_RosterSummary {
    get {return _rosterSummary ?? Flipcash_Chat_V1_RosterSummary()}
    set {_rosterSummary = newValue}
  }
  /// Returns true if `rosterSummary` has been explicitly set.
  public var hasRosterSummary: Bool {return self._rosterSummary != nil}
  /// Clears the value of `rosterSummary`. Subsequent reads from it will return its default value.
  public mutating func clearRosterSummary() {self._rosterSummary = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Kind: Equatable, Sendable {
    case memberJoined(Flipcash_Chat_V1_RosterUpdate.MemberJoined)
    case memberLeft(Flipcash_Chat_V1_RosterUpdate.MemberLeft)

  }

  /// A member joined the chat. When member is the recipient, the recipient
  /// has just become a member of the chat and should insert it into their
  /// chat list using metadata.
  public struct MemberJoined: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The member that joined, with their profile hydrated and joined_at and
    /// version set, so a client can update its cached member list without
    /// a refetch and merge later Chat.GetRoster pages against it.
    public var member: Flipcash_Chat_V1_Member {
      get {return _member ?? Flipcash_Chat_V1_Member()}
      set {_member = newValue}
    }
    /// Returns true if `member` has been explicitly set.
    public var hasMember: Bool {return self._member != nil}
    /// Clears the value of `member`. Subsequent reads from it will return its default value.
    public mutating func clearMember() {self._member = nil}

    /// The full metadata for the chat, so the recipient can insert it into
    /// their chat list without a refetch. Set only when member is the
    /// recipient; unset for every other member of the chat.
    ///
    /// The recipient inserts the chat from this snapshot, then applies the
    /// enclosing RosterUpdate.roster_summary by version like any other
    /// roster update. RosterUpdate.roster_summary is authoritative for
    /// versioning; metadata.roster_summary is not compared separately.
    public var metadata: Flipcash_Chat_V1_Metadata {
      get {return _metadata ?? Flipcash_Chat_V1_Metadata()}
      set {_metadata = newValue}
    }
    /// Returns true if `metadata` has been explicitly set.
    public var hasMetadata: Bool {return self._metadata != nil}
    /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
    public mutating func clearMetadata() {self._metadata = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _member: Flipcash_Chat_V1_Member? = nil
    fileprivate var _metadata: Flipcash_Chat_V1_Metadata? = nil
  }

  /// A member left the chat. When user_id is the recipient, the recipient is
  /// no longer a member of the chat and should remove it from their chat
  /// list.
  public struct MemberLeft: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The user that left
    public var userID: Flipcash_Common_V1_UserId {
      get {return _userID ?? Flipcash_Common_V1_UserId()}
      set {_userID = newValue}
    }
    /// Returns true if `userID` has been explicitly set.
    public var hasUserID: Bool {return self._userID != nil}
    /// Clears the value of `userID`. Subsequent reads from it will return its default value.
    public mutating func clearUserID() {self._userID = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _userID: Flipcash_Common_V1_UserId? = nil
  }

  public init() {}

  fileprivate var _rosterSummary: Flipcash_Chat_V1_RosterSummary? = nil
}

public struct Flipcash_Chat_V1_RosterUpdateBatch: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rosterUpdates: [Flipcash_Chat_V1_RosterUpdate] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ViewerState is what this chat holds about the requesting user,
/// independent of whether they are a member. It is per-viewer and never
/// shared with other members. Absent when the chat holds nothing about the
/// viewer; always present for a member, whose permissions it carries.
public struct Flipcash_Chat_V1_ViewerState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// State the viewer set for themselves through their own RPCs.
  public var settings: Flipcash_Chat_V1_ViewerState.Settings {
    get {return _settings ?? Flipcash_Chat_V1_ViewerState.Settings()}
    set {_settings = newValue}
  }
  /// Returns true if `settings` has been explicitly set.
  public var hasSettings: Bool {return self._settings != nil}
  /// Clears the value of `settings`. Subsequent reads from it will return its default value.
  public mutating func clearSettings() {self._settings = nil}

  /// What the viewer may do in this chat. Server-computed from the viewer's
  /// standing in the chat and its rules, and never derivable by the client:
  /// a client shows an affordance if and only if its flag is set. A change
  /// to any flag (e.g. the viewer being granted or losing the ability to
  /// edit) advances version and reaches the viewer's devices as a
  /// MetadataUpdate.ViewerStateChanged.
  public var permissions: Flipcash_Chat_V1_ViewerState.Permissions {
    get {return _permissions ?? Flipcash_Chat_V1_ViewerState.Permissions()}
    set {_permissions = newValue}
  }
  /// Returns true if `permissions` has been explicitly set.
  public var hasPermissions: Bool {return self._permissions != nil}
  /// Clears the value of `permissions`. Subsequent reads from it will return its default value.
  public mutating func clearPermissions() {self._permissions = nil}

  /// Advanced by exactly one on every real change to any field of this
  /// message, never by a no-op. Compared like RosterSummary.version: apply
  /// the greater value and drop the rest, so delivery order does not matter.
  /// It is not the chat event sequence and has no delta.
  public var version: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Settings: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Present if and only if the chat is muted for the viewer. Muted pushes
    /// are still delivered, flagged with push.v1.ChatMetadata.muted, and the
    /// client suppresses the notification.
    public var mute: Flipcash_Chat_V1_MuteState {
      get {return _mute ?? Flipcash_Chat_V1_MuteState()}
      set {_mute = newValue}
    }
    /// Returns true if `mute` has been explicitly set.
    public var hasMute: Bool {return self._mute != nil}
    /// Clears the value of `mute`. Subsequent reads from it will return its default value.
    public mutating func clearMute() {self._mute = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _mute: Flipcash_Chat_V1_MuteState? = nil
  }

  /// Permissions are the actions the viewer may take in the chat. Each flag
  /// is named for the RPC it gates and defaults to false, so an unset flag
  /// always means the action is not permitted.
  public struct Permissions: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Whether the viewer may call Chat.EditChat on this chat. False for
    /// every DM, and for a group member the server does not permit to
    /// edit it.
    public var canEdit: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _settings: Flipcash_Chat_V1_ViewerState.Settings? = nil
  fileprivate var _permissions: Flipcash_Chat_V1_ViewerState.Permissions? = nil
}

public struct Flipcash_Chat_V1_MuteState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var duration: Flipcash_Chat_V1_MuteState.OneOf_Duration? = nil

  /// Muted until this time, after which the mute lapses. Nothing is
  /// sent when it does, so the client owns the countdown.
  public var until: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .until(let v)? = duration {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {duration = .until(newValue)}
  }

  /// Muted forever until explicitly unmuted.
  public var forever: Flipcash_Chat_V1_MuteState.Forever {
    get {
      if case .forever(let v)? = duration {return v}
      return Flipcash_Chat_V1_MuteState.Forever()
    }
    set {duration = .forever(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Duration: Equatable, Sendable {
    /// Muted until this time, after which the mute lapses. Nothing is
    /// sent when it does, so the client owns the countdown.
    case until(SwiftProtobuf.Google_Protobuf_Timestamp)
    /// Muted forever until explicitly unmuted.
    case forever(Flipcash_Chat_V1_MuteState.Forever)

  }

  public struct Forever: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

/// IdempotencyKey lets a client safely retry a request that creates something.
/// The server derives the created object's identity from the caller and this
/// key, so a retry with the same key returns the original result instead of
/// creating a duplicate. Which parameters were sent is not part of the identity:
/// a retry with different parameters still returns the original.
///
/// The key is owned by the client and is typically a randomly generated UUID.
/// It is never exposed as the object's identity.
public struct Flipcash_Chat_V1_IdempotencyKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "flipcash.chat.v1"

extension Flipcash_Chat_V1_ChatType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0\u{1}CONTACT_DM\0\u{1}TIP_DM\0\u{1}GROUP\0")
}

extension Flipcash_Chat_V1_Metadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Metadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chat_id\0\u{1}type\0\u{1}members\0\u{3}last_message\0\u{3}last_activity\0\u{3}latest_event_sequence\0\u{3}is_hidden\0\u{1}title\0\u{1}picture\0\u{3}roster_summary\0\u{1}rules\0\u{3}viewer_state\0\u{1}creator\0\u{4}W\u{1}use_e2ee\0")

  fileprivate class _StorageClass {
    var _chatID: Flipcash_Common_V1_ChatId? = nil
    var _type: Flipcash_Chat_V1_ChatType = .unknown
    var _members: [Flipcash_Chat_V1_Member] = []
    var _lastMessage: Flipcash_Messaging_V1_Message? = nil
    var _lastActivity: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _latestEventSequence: UInt64 = 0
    var _isHidden: Bool = false
    var _title: String = String()
    var _picture: Flipcash_Blob_V1_Media? = nil
    var _rosterSummary: Flipcash_Chat_V1_RosterSummary? = nil
    var _rules: Flipcash_Chat_V1_Rules? = nil
    var _viewerState: Flipcash_Chat_V1_ViewerState? = nil
    var _creator: Flipcash_Common_V1_UserId? = nil
    var _useE2Ee: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _chatID = source._chatID
      _type = source._type
      _members = source._members
      _lastMessage = source._lastMessage
      _lastActivity = source._lastActivity
      _latestEventSequence = source._latestEventSequence
      _isHidden = source._isHidden
      _title = source._title
      _picture = source._picture
      _rosterSummary = source._rosterSummary
      _rules = source._rules
      _viewerState = source._viewerState
      _creator = source._creator
      _useE2Ee = source._useE2Ee
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._chatID) }()
        case 2: try { try decoder.decodeSingularEnumField(value: &_storage._type) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._members) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._lastMessage) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._lastActivity) }()
        case 6: try { try decoder.decodeSingularUInt64Field(value: &_storage._latestEventSequence) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._isHidden) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._title) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._picture) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._rosterSummary) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._rules) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._viewerState) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._creator) }()
        case 100: try { try decoder.decodeSingularBoolField(value: &_storage._useE2Ee) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._chatID {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if _storage._type != .unknown {
        try visitor.visitSingularEnumField(value: _storage._type, fieldNumber: 2)
      }
      if !_storage._members.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._members, fieldNumber: 3)
      }
      try { if let v = _storage._lastMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._lastActivity {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._latestEventSequence != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._latestEventSequence, fieldNumber: 6)
      }
      if _storage._isHidden != false {
        try visitor.visitSingularBoolField(value: _storage._isHidden, fieldNumber: 7)
      }
      if !_storage._title.isEmpty {
        try visitor.visitSingularStringField(value: _storage._title, fieldNumber: 8)
      }
      try { if let v = _storage._picture {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._rosterSummary {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._rules {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._viewerState {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._creator {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      if _storage._useE2Ee != false {
        try visitor.visitSingularBoolField(value: _storage._useE2Ee, fieldNumber: 100)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_Metadata, rhs: Flipcash_Chat_V1_Metadata) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._chatID != rhs_storage._chatID {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._members != rhs_storage._members {return false}
        if _storage._lastMessage != rhs_storage._lastMessage {return false}
        if _storage._lastActivity != rhs_storage._lastActivity {return false}
        if _storage._latestEventSequence != rhs_storage._latestEventSequence {return false}
        if _storage._isHidden != rhs_storage._isHidden {return false}
        if _storage._title != rhs_storage._title {return false}
        if _storage._picture != rhs_storage._picture {return false}
        if _storage._rosterSummary != rhs_storage._rosterSummary {return false}
        if _storage._rules != rhs_storage._rules {return false}
        if _storage._viewerState != rhs_storage._viewerState {return false}
        if _storage._creator != rhs_storage._creator {return false}
        if _storage._useE2Ee != rhs_storage._useE2Ee {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_Rules: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Rules"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}listener\0\u{1}speaker\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.listener) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.speaker) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.listener.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.listener, fieldNumber: 1)
    }
    if !self.speaker.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.speaker, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_Rules, rhs: Flipcash_Chat_V1_Rules) -> Bool {
    if lhs.listener != rhs.listener {return false}
    if lhs.speaker != rhs.speaker {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_ListenerRules: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListenerRules"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}minimum_balance\0\u{1}staff\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Chat_V1_MinimumBalanceRequirement?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .minimumBalance(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .minimumBalance(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Chat_V1_StaffRequirement?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .staff(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .staff(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .minimumBalance?: try {
      guard case .minimumBalance(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .staff?: try {
      guard case .staff(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_ListenerRules, rhs: Flipcash_Chat_V1_ListenerRules) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_SpeakerRules: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SpeakerRules"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}minimum_balance\0\u{1}staff\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Chat_V1_MinimumBalanceRequirement?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .minimumBalance(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .minimumBalance(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Chat_V1_StaffRequirement?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .staff(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .staff(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .minimumBalance?: try {
      guard case .minimumBalance(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .staff?: try {
      guard case .staff(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_SpeakerRules, rhs: Flipcash_Chat_V1_SpeakerRules) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_StaffRequirement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StaffRequirement"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_StaffRequirement, rhs: Flipcash_Chat_V1_StaffRequirement) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MinimumBalanceRequirement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MinimumBalanceRequirement"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}amount\0\u{1}mints\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._amount) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.mints) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._amount {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.mints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mints, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MinimumBalanceRequirement, rhs: Flipcash_Chat_V1_MinimumBalanceRequirement) -> Bool {
    if lhs._amount != rhs._amount {return false}
    if lhs.mints != rhs.mints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_Member: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Member"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{3}user_profile\0\u{1}pointers\0\u{3}joined_at\0\u{1}version\0")

  fileprivate class _StorageClass {
    var _userID: Flipcash_Common_V1_UserId? = nil
    var _userProfile: Flipcash_Profile_V1_UserProfile? = nil
    var _pointers: [Flipcash_Messaging_V1_Pointer] = []
    var _joinedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _version: UInt64 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _userID = source._userID
      _userProfile = source._userProfile
      _pointers = source._pointers
      _joinedAt = source._joinedAt
      _version = source._version
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._userID) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._userProfile) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._pointers) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._joinedAt) }()
        case 5: try { try decoder.decodeSingularUInt64Field(value: &_storage._version) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._userID {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._userProfile {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._pointers.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._pointers, fieldNumber: 3)
      }
      try { if let v = _storage._joinedAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if _storage._version != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._version, fieldNumber: 5)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_Member, rhs: Flipcash_Chat_V1_Member) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._userID != rhs_storage._userID {return false}
        if _storage._userProfile != rhs_storage._userProfile {return false}
        if _storage._pointers != rhs_storage._pointers {return false}
        if _storage._joinedAt != rhs_storage._joinedAt {return false}
        if _storage._version != rhs_storage._version {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_RosterSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterSummary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}member_count\0\u{1}version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.memberCount) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.version) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.memberCount != 0 {
      try visitor.visitSingularUInt64Field(value: self.memberCount, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularUInt64Field(value: self.version, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_RosterSummary, rhs: Flipcash_Chat_V1_RosterSummary) -> Bool {
    if lhs.memberCount != rhs.memberCount {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MetadataUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}full_refresh\0\u{3}last_activity_changed\0\u{3}viewer_state_changed\0\u{3}title_changed\0\u{3}picture_changed\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Chat_V1_MetadataUpdate.FullRefresh?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .fullRefresh(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .fullRefresh(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .lastActivityChanged(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .lastActivityChanged(v)
        }
      }()
      case 3: try {
        var v: Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .viewerStateChanged(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .viewerStateChanged(v)
        }
      }()
      case 4: try {
        var v: Flipcash_Chat_V1_MetadataUpdate.TitleChanged?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .titleChanged(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .titleChanged(v)
        }
      }()
      case 5: try {
        var v: Flipcash_Chat_V1_MetadataUpdate.PictureChanged?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .pictureChanged(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .pictureChanged(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .fullRefresh?: try {
      guard case .fullRefresh(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .lastActivityChanged?: try {
      guard case .lastActivityChanged(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .viewerStateChanged?: try {
      guard case .viewerStateChanged(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .titleChanged?: try {
      guard case .titleChanged(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .pictureChanged?: try {
      guard case .pictureChanged(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate, rhs: Flipcash_Chat_V1_MetadataUpdate) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate.FullRefresh: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MetadataUpdate.protoMessageName + ".FullRefresh"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate.FullRefresh, rhs: Flipcash_Chat_V1_MetadataUpdate.FullRefresh) -> Bool {
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MetadataUpdate.protoMessageName + ".LastActivityChanged"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_last_activity\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._newLastActivity) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._newLastActivity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged, rhs: Flipcash_Chat_V1_MetadataUpdate.LastActivityChanged) -> Bool {
    if lhs._newLastActivity != rhs._newLastActivity {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MetadataUpdate.protoMessageName + ".ViewerStateChanged"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}viewer_state\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._viewerState) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._viewerState {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged, rhs: Flipcash_Chat_V1_MetadataUpdate.ViewerStateChanged) -> Bool {
    if lhs._viewerState != rhs._viewerState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate.TitleChanged: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MetadataUpdate.protoMessageName + ".TitleChanged"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_title\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.newTitle) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.newTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.newTitle, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate.TitleChanged, rhs: Flipcash_Chat_V1_MetadataUpdate.TitleChanged) -> Bool {
    if lhs.newTitle != rhs.newTitle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MetadataUpdate.PictureChanged: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MetadataUpdate.protoMessageName + ".PictureChanged"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}new_picture\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._newPicture) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._newPicture {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MetadataUpdate.PictureChanged, rhs: Flipcash_Chat_V1_MetadataUpdate.PictureChanged) -> Bool {
    if lhs._newPicture != rhs._newPicture {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_RosterUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}member_joined\0\u{3}member_left\0\u{4}\u{8}roster_summary\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Chat_V1_RosterUpdate.MemberJoined?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .memberJoined(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .memberJoined(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Chat_V1_RosterUpdate.MemberLeft?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .memberLeft(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .memberLeft(v)
        }
      }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._rosterSummary) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .memberJoined?: try {
      guard case .memberJoined(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .memberLeft?: try {
      guard case .memberLeft(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try { if let v = self._rosterSummary {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_RosterUpdate, rhs: Flipcash_Chat_V1_RosterUpdate) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs._rosterSummary != rhs._rosterSummary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_RosterUpdate.MemberJoined: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_RosterUpdate.protoMessageName + ".MemberJoined"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}member\0\u{1}metadata\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._member) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._member {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_RosterUpdate.MemberJoined, rhs: Flipcash_Chat_V1_RosterUpdate.MemberJoined) -> Bool {
    if lhs._member != rhs._member {return false}
    if lhs._metadata != rhs._metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_RosterUpdate.MemberLeft: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_RosterUpdate.protoMessageName + ".MemberLeft"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._userID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._userID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_RosterUpdate.MemberLeft, rhs: Flipcash_Chat_V1_RosterUpdate.MemberLeft) -> Bool {
    if lhs._userID != rhs._userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_RosterUpdateBatch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RosterUpdateBatch"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}roster_updates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.rosterUpdates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.rosterUpdates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rosterUpdates, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_RosterUpdateBatch, rhs: Flipcash_Chat_V1_RosterUpdateBatch) -> Bool {
    if lhs.rosterUpdates != rhs.rosterUpdates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_ViewerState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ViewerState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}settings\0\u{1}permissions\0\u{2}\u{8}version\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._settings) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._permissions) }()
      case 10: try { try decoder.decodeSingularUInt64Field(value: &self.version) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._settings {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._permissions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.version != 0 {
      try visitor.visitSingularUInt64Field(value: self.version, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_ViewerState, rhs: Flipcash_Chat_V1_ViewerState) -> Bool {
    if lhs._settings != rhs._settings {return false}
    if lhs._permissions != rhs._permissions {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_ViewerState.Settings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_ViewerState.protoMessageName + ".Settings"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}mute\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._mute) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._mute {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_ViewerState.Settings, rhs: Flipcash_Chat_V1_ViewerState.Settings) -> Bool {
    if lhs._mute != rhs._mute {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_ViewerState.Permissions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_ViewerState.protoMessageName + ".Permissions"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}can_edit\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.canEdit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.canEdit != false {
      try visitor.visitSingularBoolField(value: self.canEdit, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_ViewerState.Permissions, rhs: Flipcash_Chat_V1_ViewerState.Permissions) -> Bool {
    if lhs.canEdit != rhs.canEdit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MuteState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MuteState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}until\0\u{1}forever\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.duration {
          hadOneofValue = true
          if case .until(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.duration = .until(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Chat_V1_MuteState.Forever?
        var hadOneofValue = false
        if let current = self.duration {
          hadOneofValue = true
          if case .forever(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.duration = .forever(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.duration {
    case .until?: try {
      guard case .until(let v)? = self.duration else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .forever?: try {
      guard case .forever(let v)? = self.duration else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MuteState, rhs: Flipcash_Chat_V1_MuteState) -> Bool {
    if lhs.duration != rhs.duration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_MuteState.Forever: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Chat_V1_MuteState.protoMessageName + ".Forever"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_MuteState.Forever, rhs: Flipcash_Chat_V1_MuteState.Forever) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Chat_V1_IdempotencyKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IdempotencyKey"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularBytesField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Chat_V1_IdempotencyKey, rhs: Flipcash_Chat_V1_IdempotencyKey) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
