// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: chat/v1/chat_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - flipcash.chat.v1.Chat

/// Namespace containing generated types for the "flipcash.chat.v1.Chat" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Flipcash_Chat_V1_Chat {
    /// Service descriptor for the "flipcash.chat.v1.Chat" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "GetChat" metadata.
        public enum GetChat {
            /// Request type for "GetChat".
            public typealias Input = Flipcash_Chat_V1_GetChatRequest
            /// Response type for "GetChat".
            public typealias Output = Flipcash_Chat_V1_GetChatResponse
            /// Descriptor for "GetChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "GetChat"
            )
        }
        /// Namespace for "GetDmChatFeed" metadata.
        public enum GetDmChatFeed {
            /// Request type for "GetDmChatFeed".
            public typealias Input = Flipcash_Chat_V1_GetDmChatFeedRequest
            /// Response type for "GetDmChatFeed".
            public typealias Output = Flipcash_Chat_V1_GetDmChatFeedResponse
            /// Descriptor for "GetDmChatFeed".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "GetDmChatFeed"
            )
        }
        /// Namespace for "GetGroupChatFeed" metadata.
        public enum GetGroupChatFeed {
            /// Request type for "GetGroupChatFeed".
            public typealias Input = Flipcash_Chat_V1_GetGroupChatFeedRequest
            /// Response type for "GetGroupChatFeed".
            public typealias Output = Flipcash_Chat_V1_GetGroupChatFeedResponse
            /// Descriptor for "GetGroupChatFeed".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "GetGroupChatFeed"
            )
        }
        /// Namespace for "StartChat" metadata.
        public enum StartChat {
            /// Request type for "StartChat".
            public typealias Input = Flipcash_Chat_V1_StartChatRequest
            /// Response type for "StartChat".
            public typealias Output = Flipcash_Chat_V1_StartChatResponse
            /// Descriptor for "StartChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "StartChat"
            )
        }
        /// Namespace for "JoinChat" metadata.
        public enum JoinChat {
            /// Request type for "JoinChat".
            public typealias Input = Flipcash_Chat_V1_JoinChatRequest
            /// Response type for "JoinChat".
            public typealias Output = Flipcash_Chat_V1_JoinChatResponse
            /// Descriptor for "JoinChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "JoinChat"
            )
        }
        /// Namespace for "LeaveChat" metadata.
        public enum LeaveChat {
            /// Request type for "LeaveChat".
            public typealias Input = Flipcash_Chat_V1_LeaveChatRequest
            /// Response type for "LeaveChat".
            public typealias Output = Flipcash_Chat_V1_LeaveChatResponse
            /// Descriptor for "LeaveChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "LeaveChat"
            )
        }
        /// Namespace for "MuteChat" metadata.
        public enum MuteChat {
            /// Request type for "MuteChat".
            public typealias Input = Flipcash_Chat_V1_MuteChatRequest
            /// Response type for "MuteChat".
            public typealias Output = Flipcash_Chat_V1_MuteChatResponse
            /// Descriptor for "MuteChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "MuteChat"
            )
        }
        /// Namespace for "UnmuteChat" metadata.
        public enum UnmuteChat {
            /// Request type for "UnmuteChat".
            public typealias Input = Flipcash_Chat_V1_UnmuteChatRequest
            /// Response type for "UnmuteChat".
            public typealias Output = Flipcash_Chat_V1_UnmuteChatResponse
            /// Descriptor for "UnmuteChat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat"),
                method: "UnmuteChat"
            )
        }
        /// Descriptors for all methods in the "flipcash.chat.v1.Chat" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetChat.descriptor,
            GetDmChatFeed.descriptor,
            GetGroupChatFeed.descriptor,
            StartChat.descriptor,
            JoinChat.descriptor,
            LeaveChat.descriptor,
            MuteChat.descriptor,
            UnmuteChat.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "flipcash.chat.v1.Chat" service.
    public static let flipcash_chat_v1_Chat = GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.chat.v1.Chat")
}

// MARK: flipcash.chat.v1.Chat (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Chat_V1_Chat {
    /// Generated client protocol for the "flipcash.chat.v1.Chat" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetChat returns the metadata for a specific chat
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetDmChatFeed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetDmChatFeed gets the set of DM chats for an owner account using
        /// > a paged API, ordered by last activity with the most recent first.
        /// > 
        /// > Chats are ordered by a mutable key (last_activity), so pagination alone
        /// > cannot guarantee a complete read: a chat can receive new activity and
        /// > move into a region the client has already paged past. To get the full
        /// > list, the client MUST combine this RPC with the event stream:
        /// > 
        /// >   1. Open the event stream to receive ChatUpdate and begin buffering updates
        /// >      BEFORE the first GetDmChatFeed call. This ordering is the contract that
        /// >      closes the gap; subscribing after pagination starts can drop chats.
        /// >   2. Page through GetDmChatFeed to exhaustion (until has_more is false),
        /// >      always echoing back the paging token returned by the prior response.
        /// >      All pages are served against a single snapshot pinned by that token,
        /// >      so the set is read consistently.
        /// >   3. Merge the buffered and ongoing stream updates onto the paginated
        /// >      set. Any chat whose activity changed after the snapshot watermark
        /// >      is delivered via the stream rather than via pagination.
        /// > 
        /// > Read together, pagination guarantees the set (every chat exactly once)
        /// > and the stream guarantees freshness and ordering. The local last_activity
        /// > sort is maintained by the client from the stream after the initial read.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetDmChatFeedRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetDmChatFeedRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetDmChatFeedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getDmChatFeed<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetDmChatFeedRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetDmChatFeedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetDmChatFeedResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetDmChatFeedResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetGroupChatFeed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetGroupChatFeed gets the set of group chats for an owner account using
        /// > a paged API, ordered by last activity with the most recent first.
        /// > 
        /// > It has the same read contract as GetDmChatFeed. Chats are ordered by a
        /// > mutable key (last_activity), so pagination alone cannot guarantee a
        /// > complete read. To get the full list, the client MUST combine this RPC
        /// > with the event stream:
        /// > 
        /// >   1. Open the event stream to receive ChatUpdate and begin buffering
        /// >      updates BEFORE the first GetGroupChatFeed call.
        /// >   2. Page through GetGroupChatFeed to exhaustion (until has_more is
        /// >      false), always echoing back the paging token returned by the prior
        /// >      response. All pages are served against a single snapshot pinned by
        /// >      that token.
        /// >   3. Merge the buffered and ongoing stream updates onto the paginated
        /// >      set. Any chat whose activity changed after the snapshot watermark
        /// >      is delivered via the stream rather than via pagination.
        /// > 
        /// > Unlike the DM feed, a group's membership can change while the feed is
        /// > being read. Every page is served only for groups the caller is still a
        /// > member of at the time of that page; a group the caller left between
        /// > pages is dropped, and its removal arrives on the stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetGroupChatFeedRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetGroupChatFeedRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetGroupChatFeedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getGroupChatFeed<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetGroupChatFeedRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetGroupChatFeedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetGroupChatFeedResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetGroupChatFeedResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "StartChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > StartChat starts a new chat.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_StartChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_StartChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_StartChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func startChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_StartChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_StartChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_StartChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_StartChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "JoinChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > JoinChat adds the caller to a chat's roster.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_JoinChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_JoinChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_JoinChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func joinChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_JoinChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_JoinChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_JoinChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_JoinChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "LeaveChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LeaveChat removes the caller from a chat's roster.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_LeaveChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_LeaveChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_LeaveChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func leaveChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_LeaveChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_LeaveChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_LeaveChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_LeaveChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "MuteChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > MuteChat mutes a chat for the caller, until a time or indefinitely.
        /// > 
        /// > Only a member may mute. Muting does not affect the event stream or
        /// > message delivery: pushes for a muted chat are still sent, flagged with
        /// > push.v1.ChatMetadata.muted, and the client suppresses the notification.
        /// > Calling it again with a different duration replaces the mute. An
        /// > identical request is a no-op. A mute is cleared when the caller leaves
        /// > the chat. Every real change reaches the caller's other devices as a
        /// > MetadataUpdate.ViewerStateChanged on the event stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_MuteChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_MuteChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_MuteChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func muteChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_MuteChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_MuteChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_MuteChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_MuteChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UnmuteChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UnmuteChat clears the caller's mute on a chat. Unmuting a chat that is
        /// > not muted is a no-op. Every real change reaches the caller's other devices
        /// > as a MetadataUpdate.ViewerStateChanged on the event stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_UnmuteChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_UnmuteChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_UnmuteChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func unmuteChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_UnmuteChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_UnmuteChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_UnmuteChatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_UnmuteChatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "flipcash.chat.v1.Chat" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetChat returns the metadata for a specific chat
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.GetChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetDmChatFeed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetDmChatFeed gets the set of DM chats for an owner account using
        /// > a paged API, ordered by last activity with the most recent first.
        /// > 
        /// > Chats are ordered by a mutable key (last_activity), so pagination alone
        /// > cannot guarantee a complete read: a chat can receive new activity and
        /// > move into a region the client has already paged past. To get the full
        /// > list, the client MUST combine this RPC with the event stream:
        /// > 
        /// >   1. Open the event stream to receive ChatUpdate and begin buffering updates
        /// >      BEFORE the first GetDmChatFeed call. This ordering is the contract that
        /// >      closes the gap; subscribing after pagination starts can drop chats.
        /// >   2. Page through GetDmChatFeed to exhaustion (until has_more is false),
        /// >      always echoing back the paging token returned by the prior response.
        /// >      All pages are served against a single snapshot pinned by that token,
        /// >      so the set is read consistently.
        /// >   3. Merge the buffered and ongoing stream updates onto the paginated
        /// >      set. Any chat whose activity changed after the snapshot watermark
        /// >      is delivered via the stream rather than via pagination.
        /// > 
        /// > Read together, pagination guarantees the set (every chat exactly once)
        /// > and the stream guarantees freshness and ordering. The local last_activity
        /// > sort is maintained by the client from the stream after the initial read.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetDmChatFeedRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetDmChatFeedRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetDmChatFeedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getDmChatFeed<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetDmChatFeedRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetDmChatFeedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetDmChatFeedResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetDmChatFeedResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.GetDmChatFeed.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetGroupChatFeed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetGroupChatFeed gets the set of group chats for an owner account using
        /// > a paged API, ordered by last activity with the most recent first.
        /// > 
        /// > It has the same read contract as GetDmChatFeed. Chats are ordered by a
        /// > mutable key (last_activity), so pagination alone cannot guarantee a
        /// > complete read. To get the full list, the client MUST combine this RPC
        /// > with the event stream:
        /// > 
        /// >   1. Open the event stream to receive ChatUpdate and begin buffering
        /// >      updates BEFORE the first GetGroupChatFeed call.
        /// >   2. Page through GetGroupChatFeed to exhaustion (until has_more is
        /// >      false), always echoing back the paging token returned by the prior
        /// >      response. All pages are served against a single snapshot pinned by
        /// >      that token.
        /// >   3. Merge the buffered and ongoing stream updates onto the paginated
        /// >      set. Any chat whose activity changed after the snapshot watermark
        /// >      is delivered via the stream rather than via pagination.
        /// > 
        /// > Unlike the DM feed, a group's membership can change while the feed is
        /// > being read. Every page is served only for groups the caller is still a
        /// > member of at the time of that page; a group the caller left between
        /// > pages is dropped, and its removal arrives on the stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_GetGroupChatFeedRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_GetGroupChatFeedRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_GetGroupChatFeedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getGroupChatFeed<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetGroupChatFeedRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_GetGroupChatFeedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_GetGroupChatFeedResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetGroupChatFeedResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.GetGroupChatFeed.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "StartChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > StartChat starts a new chat.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_StartChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_StartChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_StartChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func startChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_StartChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_StartChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_StartChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_StartChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.StartChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "JoinChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > JoinChat adds the caller to a chat's roster.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_JoinChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_JoinChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_JoinChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func joinChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_JoinChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_JoinChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_JoinChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_JoinChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.JoinChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "LeaveChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > LeaveChat removes the caller from a chat's roster.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_LeaveChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_LeaveChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_LeaveChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func leaveChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_LeaveChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_LeaveChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_LeaveChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_LeaveChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.LeaveChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "MuteChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > MuteChat mutes a chat for the caller, until a time or indefinitely.
        /// > 
        /// > Only a member may mute. Muting does not affect the event stream or
        /// > message delivery: pushes for a muted chat are still sent, flagged with
        /// > push.v1.ChatMetadata.muted, and the client suppresses the notification.
        /// > Calling it again with a different duration replaces the mute. An
        /// > identical request is a no-op. A mute is cleared when the caller leaves
        /// > the chat. Every real change reaches the caller's other devices as a
        /// > MetadataUpdate.ViewerStateChanged on the event stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_MuteChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_MuteChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_MuteChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func muteChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_MuteChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_MuteChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_MuteChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_MuteChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.MuteChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UnmuteChat" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UnmuteChat clears the caller's mute on a chat. Unmuting a chat that is
        /// > not muted is a no-op. Every real change reaches the caller's other devices
        /// > as a MetadataUpdate.ViewerStateChanged on the event stream.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Chat_V1_UnmuteChatRequest` message.
        ///   - serializer: A serializer for `Flipcash_Chat_V1_UnmuteChatRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Chat_V1_UnmuteChatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func unmuteChat<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Chat_V1_UnmuteChatRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Chat_V1_UnmuteChatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Chat_V1_UnmuteChatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_UnmuteChatResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Chat_V1_Chat.Method.UnmuteChat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Chat_V1_Chat.ClientProtocol {
    /// Call the "GetChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetChat returns the metadata for a specific chat
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_GetChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_GetChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_GetChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDmChatFeed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetDmChatFeed gets the set of DM chats for an owner account using
    /// > a paged API, ordered by last activity with the most recent first.
    /// > 
    /// > Chats are ordered by a mutable key (last_activity), so pagination alone
    /// > cannot guarantee a complete read: a chat can receive new activity and
    /// > move into a region the client has already paged past. To get the full
    /// > list, the client MUST combine this RPC with the event stream:
    /// > 
    /// >   1. Open the event stream to receive ChatUpdate and begin buffering updates
    /// >      BEFORE the first GetDmChatFeed call. This ordering is the contract that
    /// >      closes the gap; subscribing after pagination starts can drop chats.
    /// >   2. Page through GetDmChatFeed to exhaustion (until has_more is false),
    /// >      always echoing back the paging token returned by the prior response.
    /// >      All pages are served against a single snapshot pinned by that token,
    /// >      so the set is read consistently.
    /// >   3. Merge the buffered and ongoing stream updates onto the paginated
    /// >      set. Any chat whose activity changed after the snapshot watermark
    /// >      is delivered via the stream rather than via pagination.
    /// > 
    /// > Read together, pagination guarantees the set (every chat exactly once)
    /// > and the stream guarantees freshness and ordering. The local last_activity
    /// > sort is maintained by the client from the stream after the initial read.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_GetDmChatFeedRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDmChatFeed<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetDmChatFeedRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetDmChatFeedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getDmChatFeed(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_GetDmChatFeedRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_GetDmChatFeedResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetGroupChatFeed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetGroupChatFeed gets the set of group chats for an owner account using
    /// > a paged API, ordered by last activity with the most recent first.
    /// > 
    /// > It has the same read contract as GetDmChatFeed. Chats are ordered by a
    /// > mutable key (last_activity), so pagination alone cannot guarantee a
    /// > complete read. To get the full list, the client MUST combine this RPC
    /// > with the event stream:
    /// > 
    /// >   1. Open the event stream to receive ChatUpdate and begin buffering
    /// >      updates BEFORE the first GetGroupChatFeed call.
    /// >   2. Page through GetGroupChatFeed to exhaustion (until has_more is
    /// >      false), always echoing back the paging token returned by the prior
    /// >      response. All pages are served against a single snapshot pinned by
    /// >      that token.
    /// >   3. Merge the buffered and ongoing stream updates onto the paginated
    /// >      set. Any chat whose activity changed after the snapshot watermark
    /// >      is delivered via the stream rather than via pagination.
    /// > 
    /// > Unlike the DM feed, a group's membership can change while the feed is
    /// > being read. Every page is served only for groups the caller is still a
    /// > member of at the time of that page; a group the caller left between
    /// > pages is dropped, and its removal arrives on the stream.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_GetGroupChatFeedRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getGroupChatFeed<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_GetGroupChatFeedRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetGroupChatFeedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getGroupChatFeed(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_GetGroupChatFeedRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_GetGroupChatFeedResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StartChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > StartChat starts a new chat.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_StartChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func startChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_StartChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_StartChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.startChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_StartChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_StartChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "JoinChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > JoinChat adds the caller to a chat's roster.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_JoinChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func joinChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_JoinChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_JoinChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.joinChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_JoinChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_JoinChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LeaveChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LeaveChat removes the caller from a chat's roster.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_LeaveChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func leaveChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_LeaveChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_LeaveChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.leaveChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_LeaveChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_LeaveChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "MuteChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MuteChat mutes a chat for the caller, until a time or indefinitely.
    /// > 
    /// > Only a member may mute. Muting does not affect the event stream or
    /// > message delivery: pushes for a muted chat are still sent, flagged with
    /// > push.v1.ChatMetadata.muted, and the client suppresses the notification.
    /// > Calling it again with a different duration replaces the mute. An
    /// > identical request is a no-op. A mute is cleared when the caller leaves
    /// > the chat. Every real change reaches the caller's other devices as a
    /// > MetadataUpdate.ViewerStateChanged on the event stream.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_MuteChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func muteChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_MuteChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_MuteChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.muteChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_MuteChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_MuteChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnmuteChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UnmuteChat clears the caller's mute on a chat. Unmuting a chat that is
    /// > not muted is a no-op. Every real change reaches the caller's other devices
    /// > as a MetadataUpdate.ViewerStateChanged on the event stream.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Chat_V1_UnmuteChatRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unmuteChat<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Chat_V1_UnmuteChatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_UnmuteChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unmuteChat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Chat_V1_UnmuteChatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Chat_V1_UnmuteChatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Chat_V1_Chat.ClientProtocol {
    /// Call the "GetChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetChat returns the metadata for a specific chat
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getChat<Result>(
        _ message: Flipcash_Chat_V1_GetChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_GetChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDmChatFeed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetDmChatFeed gets the set of DM chats for an owner account using
    /// > a paged API, ordered by last activity with the most recent first.
    /// > 
    /// > Chats are ordered by a mutable key (last_activity), so pagination alone
    /// > cannot guarantee a complete read: a chat can receive new activity and
    /// > move into a region the client has already paged past. To get the full
    /// > list, the client MUST combine this RPC with the event stream:
    /// > 
    /// >   1. Open the event stream to receive ChatUpdate and begin buffering updates
    /// >      BEFORE the first GetDmChatFeed call. This ordering is the contract that
    /// >      closes the gap; subscribing after pagination starts can drop chats.
    /// >   2. Page through GetDmChatFeed to exhaustion (until has_more is false),
    /// >      always echoing back the paging token returned by the prior response.
    /// >      All pages are served against a single snapshot pinned by that token,
    /// >      so the set is read consistently.
    /// >   3. Merge the buffered and ongoing stream updates onto the paginated
    /// >      set. Any chat whose activity changed after the snapshot watermark
    /// >      is delivered via the stream rather than via pagination.
    /// > 
    /// > Read together, pagination guarantees the set (every chat exactly once)
    /// > and the stream guarantees freshness and ordering. The local last_activity
    /// > sort is maintained by the client from the stream after the initial read.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDmChatFeed<Result>(
        _ message: Flipcash_Chat_V1_GetDmChatFeedRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetDmChatFeedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_GetDmChatFeedRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getDmChatFeed(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetGroupChatFeed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetGroupChatFeed gets the set of group chats for an owner account using
    /// > a paged API, ordered by last activity with the most recent first.
    /// > 
    /// > It has the same read contract as GetDmChatFeed. Chats are ordered by a
    /// > mutable key (last_activity), so pagination alone cannot guarantee a
    /// > complete read. To get the full list, the client MUST combine this RPC
    /// > with the event stream:
    /// > 
    /// >   1. Open the event stream to receive ChatUpdate and begin buffering
    /// >      updates BEFORE the first GetGroupChatFeed call.
    /// >   2. Page through GetGroupChatFeed to exhaustion (until has_more is
    /// >      false), always echoing back the paging token returned by the prior
    /// >      response. All pages are served against a single snapshot pinned by
    /// >      that token.
    /// >   3. Merge the buffered and ongoing stream updates onto the paginated
    /// >      set. Any chat whose activity changed after the snapshot watermark
    /// >      is delivered via the stream rather than via pagination.
    /// > 
    /// > Unlike the DM feed, a group's membership can change while the feed is
    /// > being read. Every page is served only for groups the caller is still a
    /// > member of at the time of that page; a group the caller left between
    /// > pages is dropped, and its removal arrives on the stream.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getGroupChatFeed<Result>(
        _ message: Flipcash_Chat_V1_GetGroupChatFeedRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_GetGroupChatFeedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_GetGroupChatFeedRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getGroupChatFeed(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "StartChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > StartChat starts a new chat.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func startChat<Result>(
        _ message: Flipcash_Chat_V1_StartChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_StartChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_StartChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.startChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "JoinChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > JoinChat adds the caller to a chat's roster.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func joinChat<Result>(
        _ message: Flipcash_Chat_V1_JoinChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_JoinChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_JoinChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.joinChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "LeaveChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > LeaveChat removes the caller from a chat's roster.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func leaveChat<Result>(
        _ message: Flipcash_Chat_V1_LeaveChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_LeaveChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_LeaveChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.leaveChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "MuteChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > MuteChat mutes a chat for the caller, until a time or indefinitely.
    /// > 
    /// > Only a member may mute. Muting does not affect the event stream or
    /// > message delivery: pushes for a muted chat are still sent, flagged with
    /// > push.v1.ChatMetadata.muted, and the client suppresses the notification.
    /// > Calling it again with a different duration replaces the mute. An
    /// > identical request is a no-op. A mute is cleared when the caller leaves
    /// > the chat. Every real change reaches the caller's other devices as a
    /// > MetadataUpdate.ViewerStateChanged on the event stream.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func muteChat<Result>(
        _ message: Flipcash_Chat_V1_MuteChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_MuteChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_MuteChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.muteChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UnmuteChat" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UnmuteChat clears the caller's mute on a chat. Unmuting a chat that is
    /// > not muted is a no-op. Every real change reaches the caller's other devices
    /// > as a MetadataUpdate.ViewerStateChanged on the event stream.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unmuteChat<Result>(
        _ message: Flipcash_Chat_V1_UnmuteChatRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Chat_V1_UnmuteChatResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Chat_V1_UnmuteChatRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.unmuteChat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}