// Generated by scripts/generate-swift.sh. Do not edit.

public enum Flipcash2ContractInfo {
    public static let version = "0.10.0-dev"
    public static let protoCommit = "dd5e92db6f76700ab6b565f4eff1f9fb25140c9a"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
