// Generated by scripts/generate-swift.sh. Do not edit.

public enum Flipcash2ContractInfo {
    public static let version = "0.14.0"
    public static let protoCommit = "df1cb04e71fef7ce77a6a537e0a106fde6452a8f"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
