// Generated by scripts/generate-swift.sh. Do not edit.

public enum Flipcash2ContractInfo {
    public static let version = "0.18.0-dev"
    public static let protoCommit = "9f67566fd0297a27ad2de7a98474634adf4d3a24"

    public static var isLocal: Bool { protoCommit == localSentinel }

    public static var shortProtoCommit: String {
        isLocal ? protoCommit : String(protoCommit.prefix(shortLength))
    }

    private static let localSentinel = "LOCAL"
    private static let shortLength = 8
}
