// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: event/v1/event_streaming_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Flipcash_Event_V1_StreamEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Flipcash_Event_V1_StreamEventsRequest.OneOf_Type? = nil

  public var params: Flipcash_Event_V1_StreamEventsRequest.Params {
    get {
      if case .params(let v)? = type {return v}
      return Flipcash_Event_V1_StreamEventsRequest.Params()
    }
    set {type = .params(newValue)}
  }

  public var pong: Flipcash_Event_V1_ClientPong {
    get {
      if case .pong(let v)? = type {return v}
      return Flipcash_Event_V1_ClientPong()
    }
    set {type = .pong(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable, Sendable {
    case params(Flipcash_Event_V1_StreamEventsRequest.Params)
    case pong(Flipcash_Event_V1_ClientPong)

  }

  public struct Params: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var auth: Flipcash_Common_V1_Auth {
      get {return _auth ?? Flipcash_Common_V1_Auth()}
      set {_auth = newValue}
    }
    /// Returns true if `auth` has been explicitly set.
    public var hasAuth: Bool {return self._auth != nil}
    /// Clears the value of `auth`. Subsequent reads from it will return its default value.
    public mutating func clearAuth() {self._auth = nil}

    /// ts contains the time for stream open.
    ///
    /// It is used primarily as a nonce for auth. Server may reject
    /// timestamps that are too far in the future or past.
    public var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
      get {return _ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
      set {_ts = newValue}
    }
    /// Returns true if `ts` has been explicitly set.
    public var hasTs: Bool {return self._ts != nil}
    /// Clears the value of `ts`. Subsequent reads from it will return its default value.
    public mutating func clearTs() {self._ts = nil}

    /// What the stream is for. Optional: when nothing is set, the stream is
    /// for the signing user and carries every event addressed to them, the
    /// contract that predates this field. When set, it takes over, and the
    /// stream carries only what the target describes.
    public var target: Flipcash_Event_V1_StreamEventsRequest.Params.OneOf_Target? = nil

    public var chatPreview: Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams {
      get {
        if case .chatPreview(let v)? = target {return v}
        return Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams()
      }
      set {target = .chatPreview(newValue)}
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    /// What the stream is for. Optional: when nothing is set, the stream is
    /// for the signing user and carries every event addressed to them, the
    /// contract that predates this field. When set, it takes over, and the
    /// stream carries only what the target describes.
    public enum OneOf_Target: Equatable, Sendable {
      case chatPreview(Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams)

    }

    public init() {}

    fileprivate var _auth: Flipcash_Common_V1_Auth? = nil
    fileprivate var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  }

  /// ChatPreviewParams targets a stream at a preview of a single group chat:
  /// ChatUpdate for chat_id, under view_mode, and nothing else, for a bounded
  /// window of time. No update for any other chat, is ever delivered on it.
  ///
  /// Only group chats can be previewed. A DM has no one to preview it — a
  /// non-member of a DM may not read it under any mode — so a chat_id naming
  /// a DM is DENIED, whatever the viewer's standing and whatever the mode,
  /// by the same rule that denies every other read of it. A DM's members
  /// follow it on their user stream.
  ///
  /// The stream is time-bounded. The server fixes the lifetime of a preview
  /// at open — the bound is the server's, not the client's, and there is no
  /// way to request a longer one — and ends the stream with STREAM_EXPIRED
  /// when it elapses, whether or not anything was delivered. Pings and pongs
  /// keep the stream healthy, not alive: a pong does not extend the window.
  /// A client still previewing the chat when the window closes opens a new
  /// preview stream, and reconciles anything it missed in between the way it
  /// would after any reconnect (GetDelta for the event log, a refresh of the
  /// overlays). The server may refuse to open a preview, with DENIED, to a
  /// viewer who opens too many in too short a time.
  ///
  /// A preview is for a viewer who is not (yet) a member of the chat. A
  /// member's own chats are already carried on their user stream, which is
  /// not time-bounded, and a client should not preview a chat it is a member
  /// of; the server does not refuse it, but delivers the chat's updates on
  /// both streams. A viewer who joins the chat while previewing it switches
  /// to their user stream: the preview keeps delivering until its window
  /// closes, but is not extended by the join.
  ///
  /// The stream opens only if the viewer may read the chat under the mode,
  /// by the same rule as any other read under a messaging.v1.ViewMode: a
  /// member, or a non-member of a group who satisfies its listener rules,
  /// may read in full; a non-member of a group with listener rules they do
  /// not satisfy may read redacted; anyone else is DENIED. A chat that does
  /// not exist is NOT_FOUND. Standing is evaluated at stream open, and the
  /// server may end the stream with DENIED before the window closes if the
  /// viewer later may not read the chat under the mode — e.g. the rules
  /// changed, or they were removed from the roster.
  ///
  /// Within a ChatUpdate, the mode decides only the messages: those carried
  /// by events, and last_message in metadata_updates. Every message on the
  /// stream is delivered under the mode fixed at open, like GetDelta, never
  /// mixed, with Message.redacted set on each when redacted. Pointer,
  /// typing, reaction and roster overlays are delivered whatever the mode.
  ///
  /// A client previewing a chat redacted keeps this stream and its
  /// GetMessages/GetDelta reads under the same mode, so the events it
  /// applies are shaped like the state it applies them to (see
  /// messaging.v1.Message.redacted).
  public struct ChatPreviewParams: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The one chat whose updates are streamed. Must be a group chat; a DM
    /// is DENIED.
    public var chatID: Flipcash_Common_V1_ChatId {
      get {return _chatID ?? Flipcash_Common_V1_ChatId()}
      set {_chatID = newValue}
    }
    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool {return self._chatID != nil}
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() {self._chatID = nil}

    /// What the client intends to render of the chat, and so whether its
    /// messages may be delivered redacted (see messaging.v1.ViewMode).
    /// Unset (FULL) delivers full content to a viewer who may read the
    /// chat in full, and is DENIED to everyone else.
    public var viewMode: Flipcash_Messaging_V1_ViewMode = .full

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _chatID: Flipcash_Common_V1_ChatId? = nil
  }

  public init() {}
}

public struct Flipcash_Event_V1_StreamEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Flipcash_Event_V1_StreamEventsResponse.OneOf_Type? = nil

  public var ping: Flipcash_Event_V1_ServerPing {
    get {
      if case .ping(let v)? = type {return v}
      return Flipcash_Event_V1_ServerPing()
    }
    set {type = .ping(newValue)}
  }

  public var error: Flipcash_Event_V1_StreamEventsResponse.StreamError {
    get {
      if case .error(let v)? = type {return v}
      return Flipcash_Event_V1_StreamEventsResponse.StreamError()
    }
    set {type = .error(newValue)}
  }

  public var events: Flipcash_Event_V1_EventBatch {
    get {
      if case .events(let v)? = type {return v}
      return Flipcash_Event_V1_EventBatch()
    }
    set {type = .events(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable, Sendable {
    case ping(Flipcash_Event_V1_ServerPing)
    case error(Flipcash_Event_V1_StreamEventsResponse.StreamError)
    case events(Flipcash_Event_V1_EventBatch)

  }

  public struct StreamError: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var code: Flipcash_Event_V1_StreamEventsResponse.StreamError.Code = .denied

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum Code: SwiftProtobuf.Enum, Swift.CaseIterable {
      public typealias RawValue = Int
      case denied // = 0
      case invalidTimestamp // = 1
      case notFound // = 2
      case streamExpired // = 3
      case UNRECOGNIZED(Int)

      public init() {
        self = .denied
      }

      public init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .denied
        case 1: self = .invalidTimestamp
        case 2: self = .notFound
        case 3: self = .streamExpired
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      public var rawValue: Int {
        switch self {
        case .denied: return 0
        case .invalidTimestamp: return 1
        case .notFound: return 2
        case .streamExpired: return 3
        case .UNRECOGNIZED(let i): return i
        }
      }

      // The compiler won't synthesize support with the UNRECOGNIZED case.
      public static let allCases: [Flipcash_Event_V1_StreamEventsResponse.StreamError.Code] = [
        .denied,
        .invalidTimestamp,
        .notFound,
        .streamExpired,
      ]

    }

    public init() {}
  }

  public init() {}
}

public struct Flipcash_Event_V1_ForwardEventsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Flipcash_Event_V1_ForwardEventsRequest.OneOf_Type? = nil

  public var userEvents: Flipcash_Event_V1_UserEventBatch {
    get {
      if case .userEvents(let v)? = type {return v}
      return Flipcash_Event_V1_UserEventBatch()
    }
    set {type = .userEvents(newValue)}
  }

  public var chatEvents: Flipcash_Event_V1_ChatEventBatch {
    get {
      if case .chatEvents(let v)? = type {return v}
      return Flipcash_Event_V1_ChatEventBatch()
    }
    set {type = .chatEvents(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable, Sendable {
    case userEvents(Flipcash_Event_V1_UserEventBatch)
    case chatEvents(Flipcash_Event_V1_ChatEventBatch)

  }

  public init() {}
}

public struct Flipcash_Event_V1_ForwardEventsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Flipcash_Event_V1_ForwardEventsResponse.Result = .ok

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Result: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case ok // = 0
    case denied // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .ok
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .ok
      case 1: self = .denied
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .ok: return 0
      case .denied: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Flipcash_Event_V1_ForwardEventsResponse.Result] = [
      .ok,
      .denied,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "flipcash.event.v1"

extension Flipcash_Event_V1_StreamEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamEventsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}params\0\u{1}pong\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Event_V1_StreamEventsRequest.Params?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .params(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .params(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Event_V1_ClientPong?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .pong(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .pong(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .params?: try {
      guard case .params(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .pong?: try {
      guard case .pong(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_StreamEventsRequest, rhs: Flipcash_Event_V1_StreamEventsRequest) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_StreamEventsRequest.Params: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Event_V1_StreamEventsRequest.protoMessageName + ".Params"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}auth\0\u{1}ts\0\u{3}chat_preview\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._ts) }()
      case 3: try {
        var v: Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams?
        var hadOneofValue = false
        if let current = self.target {
          hadOneofValue = true
          if case .chatPreview(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.target = .chatPreview(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._ts {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if case .chatPreview(let v)? = self.target {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_StreamEventsRequest.Params, rhs: Flipcash_Event_V1_StreamEventsRequest.Params) -> Bool {
    if lhs._auth != rhs._auth {return false}
    if lhs._ts != rhs._ts {return false}
    if lhs.target != rhs.target {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Event_V1_StreamEventsRequest.protoMessageName + ".ChatPreviewParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chat_id\0\u{3}view_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._chatID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.viewMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._chatID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.viewMode != .full {
      try visitor.visitSingularEnumField(value: self.viewMode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams, rhs: Flipcash_Event_V1_StreamEventsRequest.ChatPreviewParams) -> Bool {
    if lhs._chatID != rhs._chatID {return false}
    if lhs.viewMode != rhs.viewMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_StreamEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamEventsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ping\0\u{1}error\0\u{1}events\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Event_V1_ServerPing?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .ping(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .ping(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Event_V1_StreamEventsResponse.StreamError?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .error(v)
        }
      }()
      case 3: try {
        var v: Flipcash_Event_V1_EventBatch?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .events(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .events(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .ping?: try {
      guard case .ping(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .events?: try {
      guard case .events(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_StreamEventsResponse, rhs: Flipcash_Event_V1_StreamEventsResponse) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_StreamEventsResponse.StreamError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Event_V1_StreamEventsResponse.protoMessageName + ".StreamError"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.code) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != .denied {
      try visitor.visitSingularEnumField(value: self.code, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_StreamEventsResponse.StreamError, rhs: Flipcash_Event_V1_StreamEventsResponse.StreamError) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_StreamEventsResponse.StreamError.Code: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DENIED\0\u{1}INVALID_TIMESTAMP\0\u{1}NOT_FOUND\0\u{1}STREAM_EXPIRED\0")
}

extension Flipcash_Event_V1_ForwardEventsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ForwardEventsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_events\0\u{3}chat_events\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Event_V1_UserEventBatch?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .userEvents(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .userEvents(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Event_V1_ChatEventBatch?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .chatEvents(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .chatEvents(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .userEvents?: try {
      guard case .userEvents(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .chatEvents?: try {
      guard case .chatEvents(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_ForwardEventsRequest, rhs: Flipcash_Event_V1_ForwardEventsRequest) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_ForwardEventsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ForwardEventsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.result) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.result != .ok {
      try visitor.visitSingularEnumField(value: self.result, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Event_V1_ForwardEventsResponse, rhs: Flipcash_Event_V1_ForwardEventsResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Event_V1_ForwardEventsResponse.Result: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OK\0\u{1}DENIED\0")
}
