// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: push/v1/model.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Flipcash_Push_V1_TokenType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0

  /// FCM registration token for an Android device
  case fcmAndroid // = 1

  /// FCM registration token or an iOS device
  case fcmApns // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .fcmAndroid
    case 2: self = .fcmApns
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .fcmAndroid: return 1
    case .fcmApns: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Flipcash_Push_V1_TokenType] = [
    .unknown,
    .fcmAndroid,
    .fcmApns,
  ]

}

/// Payload provided as extra data in a push
public struct Flipcash_Push_V1_Payload: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If present, where the app should navigate to after clicking the push
  public var navigation: Flipcash_Push_V1_Navigation {
    get {return _storage._navigation ?? Flipcash_Push_V1_Navigation()}
    set {_uniqueStorage()._navigation = newValue}
  }
  /// Returns true if `navigation` has been explicitly set.
  public var hasNavigation: Bool {return _storage._navigation != nil}
  /// Clears the value of `navigation`. Subsequent reads from it will return its default value.
  public mutating func clearNavigation() {_uniqueStorage()._navigation = nil}

  /// Ordered substitutions to apply to push title
  public var titleSubstitutions: [Flipcash_Common_V1_Substitution] {
    get {return _storage._titleSubstitutions}
    set {_uniqueStorage()._titleSubstitutions = newValue}
  }

  /// Ordered substitutions to apply to push body
  public var bodySubstitutions: [Flipcash_Common_V1_Substitution] {
    get {return _storage._bodySubstitutions}
    set {_uniqueStorage()._bodySubstitutions = newValue}
  }

  /// Push notification category
  public var category: Flipcash_Push_V1_Payload.Category {
    get {return _storage._category}
    set {_uniqueStorage()._category = newValue}
  }

  /// Push notification key for grouping pushes. If not set, then no grouping
  /// is applied.
  public var groupKey: String {
    get {return _storage._groupKey}
    set {_uniqueStorage()._groupKey = newValue}
  }

  public var chatMetadata: Flipcash_Push_V1_ChatMetadata {
    get {return _storage._chatMetadata ?? Flipcash_Push_V1_ChatMetadata()}
    set {_uniqueStorage()._chatMetadata = newValue}
  }
  /// Returns true if `chatMetadata` has been explicitly set.
  public var hasChatMetadata: Bool {return _storage._chatMetadata != nil}
  /// Clears the value of `chatMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearChatMetadata() {_uniqueStorage()._chatMetadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Category: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case `default` // = 0
    case depositWithdrawal // = 1
    case buySell // = 2
    case gain // = 3
    case chat // = 4
    case contactJoin // = 5
    case UNRECOGNIZED(Int)

    public init() {
      self = .default
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .default
      case 1: self = .depositWithdrawal
      case 2: self = .buySell
      case 3: self = .gain
      case 4: self = .chat
      case 5: self = .contactJoin
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .default: return 0
      case .depositWithdrawal: return 1
      case .buySell: return 2
      case .gain: return 3
      case .chat: return 4
      case .contactJoin: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Flipcash_Push_V1_Payload.Category] = [
      .default,
      .depositWithdrawal,
      .buySell,
      .gain,
      .chat,
      .contactJoin,
    ]

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Navigation within the app upon clicking the push
public struct Flipcash_Push_V1_Navigation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Flipcash_Push_V1_Navigation.OneOf_Type? = nil

  /// Currency info page for the provided mint 
  public var currencyInfo: Flipcash_Common_V1_PublicKey {
    get {
      if case .currencyInfo(let v)? = type {return v}
      return Flipcash_Common_V1_PublicKey()
    }
    set {type = .currencyInfo(newValue)}
  }

  /// Chat for the provided ID
  public var chatID: Flipcash_Common_V1_ChatId {
    get {
      if case .chatID(let v)? = type {return v}
      return Flipcash_Common_V1_ChatId()
    }
    set {type = .chatID(newValue)}
  }

  /// Chat for a contact with the provided phone number
  public var chatContactPhoneNumber: Flipcash_Common_V1_PhoneNumber {
    get {
      if case .chatContactPhoneNumber(let v)? = type {return v}
      return Flipcash_Common_V1_PhoneNumber()
    }
    set {type = .chatContactPhoneNumber(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable, Sendable {
    /// Currency info page for the provided mint 
    case currencyInfo(Flipcash_Common_V1_PublicKey)
    /// Chat for the provided ID
    case chatID(Flipcash_Common_V1_ChatId)
    /// Chat for a contact with the provided phone number
    case chatContactPhoneNumber(Flipcash_Common_V1_PhoneNumber)

  }

  public init() {}
}

/// Additional metadata provided for chat pushes
public struct Flipcash_Push_V1_ChatMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The user ID that sent a chat message
  ///
  /// Note: This will not be set for system messages OR for notifications that
  ///       don't relate to a user
  ///
  /// Deprecated: Infer from message instead
  public var sendingUserID: Flipcash_Common_V1_UserId {
    get {return _sendingUserID ?? Flipcash_Common_V1_UserId()}
    set {_sendingUserID = newValue}
  }
  /// Returns true if `sendingUserID` has been explicitly set.
  public var hasSendingUserID: Bool {return self._sendingUserID != nil}
  /// Clears the value of `sendingUserID`. Subsequent reads from it will return its default value.
  public mutating func clearSendingUserID() {self._sendingUserID = nil}

  /// The type of chat
  public var type: Flipcash_Chat_V1_ChatType = .unknown

  /// The chat message that was sent, if the push is for a message
  public var message: Flipcash_Messaging_V1_Message {
    get {return _message ?? Flipcash_Messaging_V1_Message()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  public var hasMessage: Bool {return self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  public mutating func clearMessage() {self._message = nil}

  /// Whether the recipient had this chat muted when the push was sent.
  /// The push is still delivered so the client can store the message,
  /// but the client must not present a notification for it.
  public var muted: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _sendingUserID: Flipcash_Common_V1_UserId? = nil
  fileprivate var _message: Flipcash_Messaging_V1_Message? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "flipcash.push.v1"

extension Flipcash_Push_V1_TokenType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN\0\u{1}FCM_ANDROID\0\u{1}FCM_APNS\0")
}

extension Flipcash_Push_V1_Payload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Payload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}navigation\0\u{3}title_substitutions\0\u{3}body_substitutions\0\u{1}category\0\u{3}group_key\0\u{3}chat_metadata\0")

  fileprivate class _StorageClass {
    var _navigation: Flipcash_Push_V1_Navigation? = nil
    var _titleSubstitutions: [Flipcash_Common_V1_Substitution] = []
    var _bodySubstitutions: [Flipcash_Common_V1_Substitution] = []
    var _category: Flipcash_Push_V1_Payload.Category = .default
    var _groupKey: String = String()
    var _chatMetadata: Flipcash_Push_V1_ChatMetadata? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _navigation = source._navigation
      _titleSubstitutions = source._titleSubstitutions
      _bodySubstitutions = source._bodySubstitutions
      _category = source._category
      _groupKey = source._groupKey
      _chatMetadata = source._chatMetadata
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._navigation) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._titleSubstitutions) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._bodySubstitutions) }()
        case 4: try { try decoder.decodeSingularEnumField(value: &_storage._category) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._groupKey) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._chatMetadata) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._navigation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._titleSubstitutions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._titleSubstitutions, fieldNumber: 2)
      }
      if !_storage._bodySubstitutions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._bodySubstitutions, fieldNumber: 3)
      }
      if _storage._category != .default {
        try visitor.visitSingularEnumField(value: _storage._category, fieldNumber: 4)
      }
      if !_storage._groupKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._groupKey, fieldNumber: 5)
      }
      try { if let v = _storage._chatMetadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Push_V1_Payload, rhs: Flipcash_Push_V1_Payload) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._navigation != rhs_storage._navigation {return false}
        if _storage._titleSubstitutions != rhs_storage._titleSubstitutions {return false}
        if _storage._bodySubstitutions != rhs_storage._bodySubstitutions {return false}
        if _storage._category != rhs_storage._category {return false}
        if _storage._groupKey != rhs_storage._groupKey {return false}
        if _storage._chatMetadata != rhs_storage._chatMetadata {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Push_V1_Payload.Category: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEFAULT\0\u{1}DEPOSIT_WITHDRAWAL\0\u{1}BUY_SELL\0\u{1}GAIN\0\u{1}CHAT\0\u{1}CONTACT_JOIN\0")
}

extension Flipcash_Push_V1_Navigation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Navigation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}currency_info\0\u{3}chat_id\0\u{3}chat_contact_phone_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Common_V1_PublicKey?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .currencyInfo(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .currencyInfo(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Common_V1_ChatId?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .chatID(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .chatID(v)
        }
      }()
      case 3: try {
        var v: Flipcash_Common_V1_PhoneNumber?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .chatContactPhoneNumber(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .chatContactPhoneNumber(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .currencyInfo?: try {
      guard case .currencyInfo(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .chatID?: try {
      guard case .chatID(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .chatContactPhoneNumber?: try {
      guard case .chatContactPhoneNumber(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Push_V1_Navigation, rhs: Flipcash_Push_V1_Navigation) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Push_V1_ChatMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sending_user_id\0\u{1}type\0\u{1}message\0\u{1}muted\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._sendingUserID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._message) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.muted) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._sendingUserID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.type != .unknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 2)
    }
    try { if let v = self._message {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.muted != false {
      try visitor.visitSingularBoolField(value: self.muted, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Push_V1_ChatMetadata, rhs: Flipcash_Push_V1_ChatMetadata) -> Bool {
    if lhs._sendingUserID != rhs._sendingUserID {return false}
    if lhs.type != rhs.type {return false}
    if lhs._message != rhs._message {return false}
    if lhs.muted != rhs.muted {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
