// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: reporting/v1/reporting_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - flipcash.reporting.v1.Reporting

/// Namespace containing generated types for the "flipcash.reporting.v1.Reporting" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Flipcash_Reporting_V1_Reporting {
    /// Service descriptor for the "flipcash.reporting.v1.Reporting" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.reporting.v1.Reporting")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Report" metadata.
        public enum Report {
            /// Request type for "Report".
            public typealias Input = Flipcash_Reporting_V1_ReportRequest
            /// Response type for "Report".
            public typealias Output = Flipcash_Reporting_V1_ReportResponse
            /// Descriptor for "Report".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.reporting.v1.Reporting"),
                method: "Report"
            )
        }
        /// Descriptors for all methods in the "flipcash.reporting.v1.Reporting" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Report.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "flipcash.reporting.v1.Reporting" service.
    public static let flipcash_reporting_v1_Reporting = GRPCCore.ServiceDescriptor(fullyQualifiedService: "flipcash.reporting.v1.Reporting")
}

// MARK: flipcash.reporting.v1.Reporting (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Reporting_V1_Reporting {
    /// Generated client protocol for the "flipcash.reporting.v1.Reporting" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Reporting lets users flag content or other users for review.
    public protocol ClientProtocol: Sendable {
        /// Call the "Report" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Report files a report against a user, chat, message, or blob. Reports
        /// > are advisory: filing one has no immediate client-visible effect and
        /// > outcomes are not surfaced back to the reporter. Reporting the same
        /// > target more than once is a no-op and returns OK.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Reporting_V1_ReportRequest` message.
        ///   - serializer: A serializer for `Flipcash_Reporting_V1_ReportRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Reporting_V1_ReportResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func report<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Reporting_V1_ReportRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Reporting_V1_ReportRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Reporting_V1_ReportResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Reporting_V1_ReportResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "flipcash.reporting.v1.Reporting" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Reporting lets users flag content or other users for review.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Report" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Report files a report against a user, chat, message, or blob. Reports
        /// > are advisory: filing one has no immediate client-visible effect and
        /// > outcomes are not surfaced back to the reporter. Reporting the same
        /// > target more than once is a no-op and returns OK.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Flipcash_Reporting_V1_ReportRequest` message.
        ///   - serializer: A serializer for `Flipcash_Reporting_V1_ReportRequest` messages.
        ///   - deserializer: A deserializer for `Flipcash_Reporting_V1_ReportResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func report<Result>(
            request: GRPCCore.ClientRequest<Flipcash_Reporting_V1_ReportRequest>,
            serializer: some GRPCCore.MessageSerializer<Flipcash_Reporting_V1_ReportRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Flipcash_Reporting_V1_ReportResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Reporting_V1_ReportResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Flipcash_Reporting_V1_Reporting.Method.Report.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Reporting_V1_Reporting.ClientProtocol {
    /// Call the "Report" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Report files a report against a user, chat, message, or blob. Reports
    /// > are advisory: filing one has no immediate client-visible effect and
    /// > outcomes are not surfaced back to the reporter. Reporting the same
    /// > target more than once is a no-op and returns OK.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Flipcash_Reporting_V1_ReportRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func report<Result>(
        request: GRPCCore.ClientRequest<Flipcash_Reporting_V1_ReportRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Reporting_V1_ReportResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.report(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Flipcash_Reporting_V1_ReportRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Flipcash_Reporting_V1_ReportResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Flipcash_Reporting_V1_Reporting.ClientProtocol {
    /// Call the "Report" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Report files a report against a user, chat, message, or blob. Reports
    /// > are advisory: filing one has no immediate client-visible effect and
    /// > outcomes are not surfaced back to the reporter. Reporting the same
    /// > target more than once is a no-op and returns OK.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func report<Result>(
        _ message: Flipcash_Reporting_V1_ReportRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Flipcash_Reporting_V1_ReportResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Flipcash_Reporting_V1_ReportRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.report(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}