// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: reporting/v1/reporting_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Flipcash_Reporting_V1_ReportRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The target being reported
  public var target: Flipcash_Reporting_V1_ReportRequest.OneOf_Target? = nil

  /// A user
  public var userID: Flipcash_Common_V1_UserId {
    get {
      if case .userID(let v)? = target {return v}
      return Flipcash_Common_V1_UserId()
    }
    set {target = .userID(newValue)}
  }

  /// A chat
  public var chatID: Flipcash_Common_V1_ChatId {
    get {
      if case .chatID(let v)? = target {return v}
      return Flipcash_Common_V1_ChatId()
    }
    set {target = .chatID(newValue)}
  }

  /// A message within a chat
  public var message: Flipcash_Reporting_V1_ReportRequest.ReportedMessage {
    get {
      if case .message(let v)? = target {return v}
      return Flipcash_Reporting_V1_ReportRequest.ReportedMessage()
    }
    set {target = .message(newValue)}
  }

  /// A blob
  public var blobID: Flipcash_Blob_V1_BlobId {
    get {
      if case .blobID(let v)? = target {return v}
      return Flipcash_Blob_V1_BlobId()
    }
    set {target = .blobID(newValue)}
  }

  /// Optional free-form text from the reporter describing the reason for
  /// the report. Not moderated or shown to other users.
  public var description_p: String = String()

  public var auth: Flipcash_Common_V1_Auth {
    get {return _auth ?? Flipcash_Common_V1_Auth()}
    set {_auth = newValue}
  }
  /// Returns true if `auth` has been explicitly set.
  public var hasAuth: Bool {return self._auth != nil}
  /// Clears the value of `auth`. Subsequent reads from it will return its default value.
  public mutating func clearAuth() {self._auth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The target being reported
  public enum OneOf_Target: Equatable, Sendable {
    /// A user
    case userID(Flipcash_Common_V1_UserId)
    /// A chat
    case chatID(Flipcash_Common_V1_ChatId)
    /// A message within a chat
    case message(Flipcash_Reporting_V1_ReportRequest.ReportedMessage)
    /// A blob
    case blobID(Flipcash_Blob_V1_BlobId)

  }

  /// ReportedMessage identifies a message. MessageId is a per-chat sequence
  /// number, so the chat it belongs to must be provided alongside it.
  public struct ReportedMessage: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var chatID: Flipcash_Common_V1_ChatId {
      get {return _chatID ?? Flipcash_Common_V1_ChatId()}
      set {_chatID = newValue}
    }
    /// Returns true if `chatID` has been explicitly set.
    public var hasChatID: Bool {return self._chatID != nil}
    /// Clears the value of `chatID`. Subsequent reads from it will return its default value.
    public mutating func clearChatID() {self._chatID = nil}

    public var messageID: Flipcash_Messaging_V1_MessageId {
      get {return _messageID ?? Flipcash_Messaging_V1_MessageId()}
      set {_messageID = newValue}
    }
    /// Returns true if `messageID` has been explicitly set.
    public var hasMessageID: Bool {return self._messageID != nil}
    /// Clears the value of `messageID`. Subsequent reads from it will return its default value.
    public mutating func clearMessageID() {self._messageID = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _chatID: Flipcash_Common_V1_ChatId? = nil
    fileprivate var _messageID: Flipcash_Messaging_V1_MessageId? = nil
  }

  public init() {}

  fileprivate var _auth: Flipcash_Common_V1_Auth? = nil
}

public struct Flipcash_Reporting_V1_ReportResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Flipcash_Reporting_V1_ReportResponse.Result = .ok

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Result: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case ok // = 0
    case denied // = 1
    case notFound // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .ok
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .ok
      case 1: self = .denied
      case 2: self = .notFound
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .ok: return 0
      case .denied: return 1
      case .notFound: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Flipcash_Reporting_V1_ReportResponse.Result] = [
      .ok,
      .denied,
      .notFound,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "flipcash.reporting.v1"

extension Flipcash_Reporting_V1_ReportRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReportRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_id\0\u{3}chat_id\0\u{1}message\0\u{3}blob_id\0\u{1}description\0\u{2}\u{5}auth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Flipcash_Common_V1_UserId?
        var hadOneofValue = false
        if let current = self.target {
          hadOneofValue = true
          if case .userID(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.target = .userID(v)
        }
      }()
      case 2: try {
        var v: Flipcash_Common_V1_ChatId?
        var hadOneofValue = false
        if let current = self.target {
          hadOneofValue = true
          if case .chatID(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.target = .chatID(v)
        }
      }()
      case 3: try {
        var v: Flipcash_Reporting_V1_ReportRequest.ReportedMessage?
        var hadOneofValue = false
        if let current = self.target {
          hadOneofValue = true
          if case .message(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.target = .message(v)
        }
      }()
      case 4: try {
        var v: Flipcash_Blob_V1_BlobId?
        var hadOneofValue = false
        if let current = self.target {
          hadOneofValue = true
          if case .blobID(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.target = .blobID(v)
        }
      }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._auth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.target {
    case .userID?: try {
      guard case .userID(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .chatID?: try {
      guard case .chatID(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .message?: try {
      guard case .message(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .blobID?: try {
      guard case .blobID(let v)? = self.target else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 5)
    }
    try { if let v = self._auth {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Reporting_V1_ReportRequest, rhs: Flipcash_Reporting_V1_ReportRequest) -> Bool {
    if lhs.target != rhs.target {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs._auth != rhs._auth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Reporting_V1_ReportRequest.ReportedMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Flipcash_Reporting_V1_ReportRequest.protoMessageName + ".ReportedMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}chat_id\0\u{3}message_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._chatID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._messageID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._chatID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._messageID {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Reporting_V1_ReportRequest.ReportedMessage, rhs: Flipcash_Reporting_V1_ReportRequest.ReportedMessage) -> Bool {
    if lhs._chatID != rhs._chatID {return false}
    if lhs._messageID != rhs._messageID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Reporting_V1_ReportResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReportResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.result) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.result != .ok {
      try visitor.visitSingularEnumField(value: self.result, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Flipcash_Reporting_V1_ReportResponse, rhs: Flipcash_Reporting_V1_ReportResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Flipcash_Reporting_V1_ReportResponse.Result: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0OK\0\u{1}DENIED\0\u{1}NOT_FOUND\0")
}
